import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import useSwr from "swr";
import Metamask from "./metamask";

const fetcher = (url: string) => fetch(url).then((res) => res.json());

const Home: NextPage = () => {
  const { data, error } = useSwr("/api/hello", fetcher);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Metamask></Metamask>
        <button>Hit it fam</button>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
